Ft/wisdom/founders terms policy
The-Intern-Place/TiP_Frontend pull request #25
Opened 2024-07-14 05:35 UTC by Ajinormotor

## Description

Please include a summary of the changes and the related issue.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots (if applicable):

2024-07-14 18:47 UTC, Blossom1-chike requested changes
also, link the various pages to their corresponding texts on the footer

2024-07-14 18:47 UTC, Blossom1-chike commented on src/chunks/founders-template-chunk/founders-hero-section-chunk/FoundersHeroTemplateChunk.tsx
> +              className="font-[400] text-[18px] w-full font-epilogue text-[#1B1B1B99]
confirm the color of this text with that on figma

2024-07-14 18:47 UTC, Blossom1-chike commented on src/chunks/founders-template-chunk/founders-hero-section-chunk/FoundersHeroTemplateChunk.tsx
> +            <button
use button component here

2024-07-14 18:47 UTC, Blossom1-chike commented on src/chunks/founders-template-chunk/founders-all-template-chunk/FoundersAllTemplateChunk.tsx
> +          <h1 className="font-clash font-[600] text-[32px] leading-[38px] text-[#1B1B1B]">
move the what we offer and founder section to another page, this file has a lot of lines already

2024-07-14 18:47 UTC, Blossom1-chike commented on src/components/cards/founders-offer-card/FoundersOfferCard.tsx
> +      className="flex flex-col border-[1px] rounded-[20px] border-light-blueb bg-[#FFFFFF]
there's a type with this border color, check it out

2024-07-14 18:47 UTC, Blossom1-chike commented on src/chunks/founders-template-chunk/founders-all-template-chunk/FoundersAllTemplateChunk.tsx
> +          <p className="font-clash font-[400] text-[18px] leading-[32px] md:my-[2.2rem] text-grey gap-[10px]">
on the design, this font is epilogue, please confirm this

2024-07-15 16:31 UTC, Ajinormotor commented on src/chunks/founders-template-chunk/founders-hero-section-chunk/FoundersHeroTemplateChunk.tsx
> +            <button
i shoud remove the div container?

2024-07-15 16:53 UTC, Ajinormotor commented
made the necessary correction highlights

2024-07-22 06:17 UTC, Blossom1-chike approved these changes
changes reviewed

2024-07-22 07:06 UTC, merged