Ft/wisdom/dashboard/application
The-Intern-Place/TiP_Frontend pull request #41
Opened 2024-08-20 12:47 UTC by Ajinormotor

## Description

Please include a summary of the changes and the related issue.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots (if applicable):

2024-08-21 07:57 UTC, Ajinormotor commented
am done with dashboard application, if any correction?

2024-08-26 16:50 UTC, Blossom1-chike requested changes

2024-08-26 16:50 UTC, Blossom1-chike commented on src/chunks/admin-template-chunk/application-template-chunk/ApplicationTemplateChunk.tsx
> +      <div className="w-full h-[46px] flex border-b-[1px] border-[#D6DDEB] gap-[60px]">
![image](https://github.com/user-attachments/assets/8b0e38a2-9816-4ea0-9ba9-cfdc27d96f69)

compare this image with what you have, the font sizr, weight and style, please update.
also, move this filter tab into a component of its own and then use it here so its reusable

2024-08-26 16:50 UTC, Blossom1-chike commented on src/chunks/admin-template-chunk/application-template-chunk/ApplicationTemplateChunk.tsx
> +            July
work on this implementation such that when clicked, it shows a calendar where one can select date. make it functional

2024-08-26 16:50 UTC, Blossom1-chike commented on src/chunks/admin-template-chunk/application-template-chunk/ApplicationTemplateChunk.tsx
for the tables, i dont think each filter should have different data, the whole idea is that the filters same data for the different tables, so please look into the implementation, we can look through it together when you're available

2024-08-30 05:19 UTC, Ajinormotor commented
i have worked on all the changes you requested;
Made the calender fucntional
Each table with the necessary filter
worked on the font size  etc

2024-09-12 21:21 UTC, Blossom1-chike approved these changes

2024-09-12 21:22 UTC, merged